# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:

name: Lint and test after every push or pull request
on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests (${{ matrix.os }}, ${{ matrix.env }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macos-latest
        env:
          - ci/python_310.yaml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: r5py
          channel-priority: strict
          channels: conda-forge
          environment-file: ${{ matrix.env }}
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true

      - name: Install JVM (using mamba)
        shell: bash -l {0}
        run: |
          which conda
          conda install 'openjdk>=11,<12'
          which mamba
          mamba install 'openjdk>=11,<12'
